  
#---------------------------------------------------------------------#
#     Trilium  notes  service                                         #
#---------------------------------------------------------------------#
 
  trilium:
    container_name: trilium
    # Optionally, replace `latest` with a version tag like `v0.90.3`
    # Using `latest` may cause unintended updates to the container
    image: triliumnext/trilium:latest
    # Restart the container unless it was stopped by the user
    restart: unless-stopped
    env_file:
      - ./services/trilium/trilium.env    
    ports:
      # By default, Trilium will be available at http://localhost:8080
      # It will also be accessible at http://<host-ip>:8080
      # You might want to limit this with something like Docker Networks, reverse proxies, or firewall rules,
      # however be aware that using UFW is known to not work with default Docker installations, see:
      # https://docs.docker.com/engine/network/packet-filtering-firewalls/#docker-and-ufw
      # in this set of apps i need others ot be on port 80 so i changed it in 3 places to 8111 you can also do the same if it conflicts with your own apps
      - '8111:8080'
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      # This can also be changed with by replacing the line below with `- /path/of/your/choice:/home/node/trilium-data
      - ./volumes/trilium/trilium-data:/home/node/trilium-data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"http\").get(\"http://localhost:8080/api/health-check\", (res) => { if (res.statusCode === 200) { process.exit(0); } else { process.exit(1); } }).on(\"error\", (e) => { process.exit(1); });'"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s 
    labels:
      - homepage.group=OFFICE
      - homepage.name=trilium
      - homepage.icon=trilium.svg
      - homepage.href=http://${SYSTEM_HOSTNAME:-rpi4-red}.local:8111
      - homepage.description=notes manager    
    networks:
      private_network:
        ipv4_address: 172.19.0.50 # internal address of trilium
    
 