  
#---------------------------------------------------------------------#
#     OMNI-TOOLS                                                      #
#---------------------------------------------------------------------#  
   
  omni-tools:
    image: iib0011/omni-tools:latest
    container_name: omni-tools
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - ./services/omni-tools/omni-tools.env
    networks:
        private_network:
          ipv4_address: 172.19.0.56 # internal address of omni-tools