 
#---------------------------------------------------------------------#
#     PI-HOLE ad block                                                #
#---------------------------------------------------------------------# 
  
  pihole: # More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      #- "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    healthcheck:
      test: ["CMD", "wget", "-q", "-T", "15", "-O", "/dev/null", "http://localhost:80/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3  
    # Volumes store your data between container upgrades or use env file
    env_file:
      - ./services/pihole/pihole.env
    volumes:
      - ./volumes/pihole/etc-pihole/:/etc/pihole/
      - ./volumes/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed

    restart: always
    labels:
      - homepage.group=NETWORK
      - homepage.name=pi-hole
      - homepage.icon=pi-hole.png
      - homepage.href=http://${SYSTEM_HOSTNAME:-rpi4-red}.local:80/admin
      - homepage.description=ad blocker
    networks:
      private_network:
        ipv4_address: 172.19.0.3 # internal address of pihole
