  
#---------------------------------------------------------------------#
#     vaultwarden                                                     #
#---------------------------------------------------------------------#  
  
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    env_file:
        - ./services/vaultwarden/vaultwarden.env  
    volumes:
      - ./volumes/vaultwarden/vw-data/:/data/
    labels:
        - homepage.group=OFFICE
        - homepage.name=Vaultwarden
        - homepage.icon=vaultwarden.svg
        - homepage.href=hostname.your-tailnet-name.ts.net
        - homepage.description=Password Manager      
    networks:
      private_network:
        ipv4_address: 172.19.0.51