  
#---------------------------------------------------------------------#
#     caddy                                                           #
#---------------------------------------------------------------------#  
  
  caddy:
      image: caddy:latest
      container_name: caddy
      restart: always
      ports:
        - "80:80"
        - "443:443"
        - "8443:8443" # For Homebox
      volumes:
        - ${VOLUMES_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
        - ${VOLUMES_DIR}/caddy/caddy_data:/data
        - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock:ro
      depends_on:
        - vaultwarden
      labels:
      - homepage.group=OFFICE
      - homepage.name=caddy
      - homepage.icon=caddy.png
      - homepage.description=reverse proxy 
      networks:
        private_network:
