  
#---------------------------------------------------------------------#
#     IMMICH  power tools                                             #
#---------------------------------------------------------------------#  
   
  power-tools:
    container_name: immich_power_tools
    image: ghcr.io/immich-power-tools/immich-power-tools:latest
    user: "1000:1000"
    volumes:
      - ./volumes/immich-power-tools/immich-power-tools-data:/app/data
    ports:
      - "8001:3000"
    env_file:
      - ./services/immich-power-tools/immich-power-tools.env
    networks:
        private_network:
          ipv4_address: 172.19.0.55 # internal address of immich power tools